### ISSUE TITLE
Installing services failure

### ISSUE THREAD

**Issue by Originalas** [Marocco2/AM-GApps-Tool#1]
Listing ADB Devices
- daemon not running. starting it now on port 5037 *
- daemon started successfully *
  List of devices attached
  emulator-5554   device
## 

Configuring Gapps from tmp data
mount: can't read '/proc/mounts': No such file or directory
Installing services
534 KB/s (10303033 bytes in 18.835s)
        pkg: /data/local/tmp/com.android.vending.apk
Failure [INSTALL_FAILED_(-2147009274)]
464 KB/s (3196914 bytes in 6.714s)
        pkg: /data/local/tmp/com.google.android.gsf.login.apk
Failure [DELETING_EXISTING_APPLICATIONDATA_STORE_FAILED]
511 KB/s (10490220 bytes in 20.044s)

**Comment by ADeltaX** [comment]
You need to perform a hard reset before executing this script.

**Comment by Marocco2** [comment]
Same, also with HR.

**Comment by erezak** [comment]
Same here. Also after HR
