### ISSUE TITLE
Lumia 720 support

### ISSUE THREAD

**Issue by Malavos** [Marocco2/AM-GApps-Tool#10]
Does this app works fine on Lumia 720? Couldn't manage it to work, although I'm using slow insider version.

**Comment by Marocco2** [comment]
It isn't only for 720, but all Lumias

**Comment by Malavos** [comment]
But it crashes on my lumia 720 and I can't make it work. The error code is 14.

Enviado pelo meu Windows Phone

**Comment by Marocco2** [comment]
So it's another problem, that isn't associated to this tool. See this post http://forum.xda-developers.com/windows-phone-8/general/apk-installed-unsupported-devices-sd-t3175843

**Comment by Malavos** [comment]
But I can't even install the tool. It causes that error code while installing. Is that really related?

Enviado pelo meu Windows Phone

**Comment by Marocco2** [comment]
To install the tool, it is required get the Astoria platform. Currently, you don't have that. You can follow that link and hope for the best.

**Comment by Malavos** [comment]
Thank you, I will follow that.
:) can you close the issue? Im answering by my mobile mail.

Enviado pelo meu Windows Phone
