### ISSUE TITLE
[INSTALL_FAILED_VERSION_DOWNGRADE]

### ISSUE THREAD

**Issue by vclima** [Marocco2/AM-GApps-Tool#2]
On step 2 I keep getting this error, and no play store or google play services/ google login appears on my recent installed apps, only the others (youtube, keep, etc).
## Killing ADB Server

Launching wconnect as usb
Creating session...
## emulator-5554 on USB connected.

Listing ADB Devices
- daemon not running. starting it now on port 5037 *
- daemon started successfully *
  List of devices attached
  emulator-5554   device
## 

Configuring Gapps from tmp data
Installing services
736 KB/s (10303033 bytes in 13.664s)
        pkg: /data/local/tmp/com.android.vending.apk
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
776 KB/s (3196914 bytes in 4.018s)
        pkg: /data/local/tmp/com.google.android.gsf.login.apk
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

**Comment by Marocco2** [comment]
Seems like you have done this before.

**Comment by vclima** [comment]
Yes,I screwed up on step 3 copying those files to RootFS>system>... That's why I reseted, that should have deleted everything right?

**Comment by Marocco2** [comment]
Follow uninstall guide.
